name: CI/CD Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100
    
    - name: Restore dependencies
      run: dotnet restore Sources/OpenLibraryWS_Wrapper.sln
    
    - name: Build
      run: |
        dotnet build Sources/OpenLibraryWS_Wrapper.sln -c Release --no-restore
        dotnet publish Sources/OpenLibraryWrapper/OpenLibraryWrapper.csproj -c Release --no-restore -o $GITHUB_WORKSPACE/build/release

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100
    
    - name: Test
      run: dotnet test Sources/OpenLibraryWS_Wrapper.sln --no-restore 
  
  # Additional jobs (analyze, docs, deploy, etc.) can be added similarly
